import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer/Footer";

const inter = Inter({
  // weight: ["400", "500","600", "700", "900"],
  // style: ["normal", "italic"],
  subsets: ["latin"],
  // display: "swap",
});

export const metadata = {
  title: "Astify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Menu>
            {children}
            <Footer/>
          </Menu>
        </Providers>
      </body>
    </html>
  );
}
